local GlobalEnumDefine = class("GlobalEnumDefine")
GlobalEnumDefine.EPlatformType = {PC = 0, Mobile = 1}
local ERewardModule = {}
GlobalEnumDefine.ERewardModule = ERewardModule
ERewardModule.Rank = 1
ERewardModule.Suvrey = 2
local EItemOperateStateType = {}
GlobalEnumDefine.EItemOperateStateType = EItemOperateStateType
EItemOperateStateType.Equiped = 0
EItemOperateStateType.NotEquip = 1
EItemOperateStateType.NotUnlcok = 2
local EItemUnlockConditionType = {}
GlobalEnumDefine.EItemUnlockConditionType = EItemUnlockConditionType
EItemUnlockConditionType.None = 0
EItemUnlockConditionType.Store = 1
EItemUnlockConditionType.BattlePass = 2
EItemUnlockConditionType.Lottery = 3
EItemUnlockConditionType.AccountLevel = 4
EItemUnlockConditionType.Activity = 5
local ERoleSkillType = {}
GlobalEnumDefine.ERoleSkillType = ERoleSkillType
ERoleSkillType.Active = 1
ERoleSkillType.Passive = 2
ERoleSkillType.Unique = 3
local PlayerAttributeType = {}
GlobalEnumDefine.PlayerAttributeType = PlayerAttributeType
PlayerAttributeType.emNick = 1
PlayerAttributeType.emSex = 2
PlayerAttributeType.emEXP = 3
PlayerAttributeType.emLevel = 4
PlayerAttributeType.emCrystal = 5
PlayerAttributeType.emIcon = 7
PlayerAttributeType.emLogin = 8
PlayerAttributeType.emIdeal = 9
PlayerAttributeType.emExplore = 10
PlayerAttributeType.emLogout = 11
PlayerAttributeType.emWeaponScrap = 12
PlayerAttributeType.emRoleScrap = 13
PlayerAttributeType.emVCardAvatarID = 31
PlayerAttributeType.emVCardFrameId = 32
PlayerAttributeType.emVCardBorderID = 33
PlayerAttributeType.emVCardAchieId = 34
PlayerAttributeType.emCrystalIncRate = 51
PlayerAttributeType.emIdealIncRate = 52
PlayerAttributeType.emExpIncRate = 53
PlayerAttributeType.emRoleExpIncRate = 54
PlayerAttributeType.emWeaponExpIncRate = 55
PlayerAttributeType.emBanChatTime = 105
PlayerAttributeType.emBanChatReason = 108
PlayerAttributeType.emMax = 1000
local ECommunicationType = {}
GlobalEnumDefine.ECommunicationType = ECommunicationType
ECommunicationType.None = 0
ECommunicationType.RoleAction = 1
ECommunicationType.RoleVoice = 2
local EBattlePassTaskType = {}
GlobalEnumDefine.EBattlePassTaskType = EBattlePassTaskType
EBattlePassTaskType.kNone = 0
EBattlePassTaskType.kDayTask = 1
EBattlePassTaskType.kWeekTask = 2
EBattlePassTaskType.kLoopTask = 3
EBattlePassTaskType.kApartmentTask = 4
EBattlePassTaskType.KActivityTask = 5
local EPageModelPreviewType = {}
GlobalEnumDefine.EPageModelPreviewType = EPageModelPreviewType
EPageModelPreviewType.None = 0
EPageModelPreviewType.Preview = 1
EPageModelPreviewType.Normal = 2
local EGameModeType = {}
GlobalEnumDefine.EGameModeType = EGameModeType
EGameModeType.None = 0
EGameModeType.Team = 1
EGameModeType.Bomb = 2
EGameModeType.Room = 3
EGameModeType.RankTeam = 4
EGameModeType.RankBomb = 5
EGameModeType.Mine = 6
local EPlayModeType = {}
GlobalEnumDefine.EPlayModeType = EPlayModeType
EPlayModeType.None = 0
EPlayModeType.Team = 1
EPlayModeType.Bomb = 2
EPlayModeType.Mine = 3
local EKaChatPledgeType = {}
GlobalEnumDefine.EKaChatPledgeType = EKaChatPledgeType
EKaChatPledgeType.Text = 0
EKaChatPledgeType.RoleRoom = 1
EKaChatPledgeType.RoleFile = 2
EKaChatPledgeType.RoleBiography = 3
EKaChatPledgeType.Plot3D = 4
EKaChatPledgeType.PledgeTask = 5
local EApartmentPageType = {}
GlobalEnumDefine.EApartmentPageType = EApartmentPageType
EApartmentPageType.Main = 1
EApartmentPageType.Promise = 2
EApartmentPageType.Profile = 3
local EActivityStatus = {}
EActivityStatus.Preview = 1
EActivityStatus.Runing = 2
EActivityStatus.Expire = 3
EActivityStatus.Closed = 4
GlobalEnumDefine.EActivityStatus = EActivityStatus
local EActivityType = {}
EActivityType.Hot = 1
EActivityType.Nomal = 2
EActivityType.Limited = 3
EActivityType.classic = 4
GlobalEnumDefine.EActivityType = EActivityType
local EActivityStyle = {}
EActivityStyle.Banner = 1
EActivityStyle.IconAndTip = 2
GlobalEnumDefine.EActivityStyle = EActivityStyle
local ESpaceTimeStages = {}
ESpaceTimeStages.None = 0
ESpaceTimeStages.Flip = 1
ESpaceTimeStages.Send = 2
ESpaceTimeStages.Shut = 3
GlobalEnumDefine.ESpaceTimeStages = ESpaceTimeStages
local ECardStatus = {}
ECardStatus.None = 0
ECardStatus.Expire = 1
ECardStatus.Opened = 2
ECardStatus.Activate = 3
ECardStatus.Locked = 4
GlobalEnumDefine.ECardStatus = ECardStatus
local EMusicRewardStatus = {}
EMusicRewardStatus.None = 0
EMusicRewardStatus.Get = 1
EMusicRewardStatus.Activate = 2
EMusicRewardStatus.Locked = 3
GlobalEnumDefine.EMusicRewardStatus = EMusicRewardStatus
local EItemQuality = {}
EItemQuality.Initial = 0
EItemQuality.Excellent = 1
EItemQuality.Exquisite = 2
EItemQuality.Superior = 3
EItemQuality.Perfect = 4
EItemQuality.Legendary = 5
GlobalEnumDefine.EItemQuality = EItemQuality
local EApartmentNavigation = {}
EApartmentNavigation.None = 0
EApartmentNavigation.ShowList = 1
EApartmentNavigation.ShowNewGuideDefault = 2
EApartmentNavigation.ShowApartmentDefault = 3
EApartmentNavigation.ShowAllDefault = 4
GlobalEnumDefine.EApartmentNavigation = EApartmentNavigation
local ESecondPanelAlignment = {}
GlobalEnumDefine.ESecondPanelAlignment = ESecondPanelAlignment
ESecondPanelAlignment.None = 0
ESecondPanelAlignment.BelowRight = 1
ESecondPanelAlignment.CenterRight = 2
ESecondPanelAlignment.AboveRight = 3
ESecondPanelAlignment.AboveCenter = 4
ESecondPanelAlignment.BelowCenter = 5
ESecondPanelAlignment.BelowLeft = 6
ESecondPanelAlignment.CenterLeft = 7
ESecondPanelAlignment.AboveLeft = 8
local EStoreType = {}
GlobalEnumDefine.EStoreType = EStoreType
EStoreType.GiftAway = 0
EStoreType.SingleProduct = 1
EStoreType.NoDiscountPackage = 2
EStoreType.DiscountPackage = 3
EStoreType.SingleProductCantBuy = 4
local EHermesScrollBarStateType = {}
GlobalEnumDefine.EHermesScrollBarStateType = EHermesScrollBarStateType
EHermesScrollBarStateType.Default = 1
EHermesScrollBarStateType.Working = 2
EHermesScrollBarStateType.Pause = 3
EHermesScrollBarStateType.UnPause = 4
_G.GlobalEnumDefine = GlobalEnumDefine
return GlobalEnumDefine
